name: etl
channels:
 - conda-forge
dependencies:
  - python=3.9*
  - pip
  - s3fs
  - dask
  - distributed
  - pandas<1.4
  - fsspec
  - numcodecs
  - prefect=1.2.4
  - xarray
  - netcdf4
  - scipy
  - zarr
  - intake
  - dask-geopandas
  - intake-geopandas
  - pyarrow
  - dataretrieval
  - timezonefinder
  - numba
  - hvplot
  - xesmf
  - clisops
  - dask-geopandas
  - ipython
  - pip:
      - pangeo-forge-recipes
      - git+https://github.com/hydrologie/xdatasets.git
